// Generated by scripts/sync-run.mjs from ../runs/day9/run.json. Do not hand edit.
// Regenerate rather than correcting a number here, so the film cannot drift from
// the run that produced it.

export type Estimate = {
  value: number;
  interval: [number, number];
  n: number;
};

export const RUN = {
  "runId": null,
  "sourceFile": "../runs/day9/run.json",
  "demo": {
    "queryId": "CO-02",
    "question": "At what age should someone whose parent had colon cancer start getting screening colonoscopies?",
    "product": "chatgpt",
    "sourceCount": 2,
    "claims": [
      {
        "id": "CO-02#229c466d",
        "text": "If your parent was diagnosed before age 60: Start a colonoscopy at age 40 OR 10 years before your parent's age at diagnosis, whichever comes first.",
        "markers": [
          "ACG"
        ],
        "verdict": "SUPPORTED",
        "span": "Persons with a family history of CRC or a documented advanced adenoma in a first-degree relative age <60 years or 2 first-degree relatives with these findings at any age are recommended to undergo screening by colonoscopy every 5 years, beginning 10 years before the age at diagnosis of the youngest affected relative or age 40, whichever is earlier."
      },
      {
        "id": "CO-02#bd859ac4",
        "text": "Colonoscopy is generally repeated every 5 years if the results are normal.",
        "markers": [
          "ACG"
        ],
        "verdict": "NOT_SUPPORTED",
        "span": ""
      },
      {
        "id": "CO-02#ec346390",
        "text": "If your parent was diagnosed at age 60 or older: Start screening at age 40.",
        "markers": [
          "GI Webfiles"
        ],
        "verdict": "COULD_NOT_VERIFY",
        "span": ""
      },
      {
        "id": "CO-02#8be1dd14",
        "text": "Colonoscopy is one option, and if the first test is normal, the interval can generally follow average-risk screening intervals.",
        "markers": [
          "GI Webfiles"
        ],
        "verdict": "COULD_NOT_VERIFY",
        "span": ""
      },
      {
        "id": "CO-02#98e0bdb6",
        "text": "Parent diagnosed at        When you should start 45        35 50        40 55        40 62        40 70        40",
        "markers": [],
        "verdict": "COULD_NOT_VERIFY",
        "span": ""
      },
      {
        "id": "CO-02#11750893",
        "text": "if your father was diagnosed with colon cancer at 52, you would generally begin colonoscopy at age 40 (because 10 years earlier would be 42, but the guideline uses the earlier of age 40 or 10 years before diagnosis).",
        "markers": [
          "ACG"
        ],
        "verdict": "SUPPORTED",
        "span": "Persons with a family history of CRC or a documented advanced adenoma in a first-degree relative age <60 years or 2 first-degree relatives with these findings at any age are recommended to undergo screening by colonoscopy every 5 years, beginning 10 years before the age at diagnosis of the youngest affected relative or age 40, whichever is earlier."
      },
      {
        "id": "CO-02#68bb157b",
        "text": "Multiple affected first-degree relatives can warrant more intensive screening.",
        "markers": [
          "GI Webfiles"
        ],
        "verdict": "COULD_NOT_VERIFY",
        "span": ""
      }
    ],
    "withheld": [
      "INSUFFICIENT_EVIDENCE: more than half this answer's cited claims produced no verdict that stands, so a support rate over the remainder would be a rate over whatever happened to be readable rather than over the answer."
    ],
    "withheldCode": "INSUFFICIENT_EVIDENCE"
  },
  "kappa": {
    "value": 0.304,
    "interval": [
      0.004,
      0.604
    ],
    "n": 35
  },
  "perClass": [
    {
      "label": "the page does not say this",
      "verdict": "NOT_FOUND_IN_SOURCE",
      "precision": 77.3,
      "interval": [
        56.6,
        89.9
      ],
      "n": 22
    },
    {
      "label": "the page partly says this",
      "verdict": "PARTIALLY_SUPPORTED",
      "precision": 16.7,
      "interval": [
        3,
        56.4
      ],
      "n": 6
    }
  ],
  "perClassGap": 0.21,
  "notFoundInSource": {
    "precision": 77.3,
    "recall": 77.3,
    "n": 22
  },
  "partiallySupported": {
    "precision": 16.7,
    "n": 6
  }
} as const;
